apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs-server-ip
    path: "/postgres-data"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage-class
provisioner: kubernetes.io/nfs
parameters:
  archiveOnDelete: "false"
  mountOptions: "hard,nfsvers=3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: secretpassword
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: pv-postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage-class
  resources:
    requests:
      storage: 10Gi
